stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: for D in */; do docker build "${D}"; done

job 2:
  stage: test
  script: echo "This step is not done"

job 3:
  stage: deploy
  script: docker-compose up --build -d
  