stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: for D in */; do docker build "${D}"; done

job 2:
  stage: test
  script: echo "No tests yet :'("

job 3:
  stage: deploy
  script: docker-compose up -f docker-compose.yml -f docker-compose.prod.yml --build -d
