version: '3'
services:
  api:
    build: ./api
#  sensors:
#    build: ./sensors
    environment:
      #SIMULATE_SENSORS: please do
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /db
    volumes:
      - "/db:/db" #share /db with host
  webserver:
    build: ./webserver
    ports:
      - 80:80
      - 443:443
#    volumes:
#      - "well_known:/webroot/.well_known" #share volume with certbot
  #certbot:
    #image: certbot
    # run in webroot mode
    # share validation folder with webserver in appropriate directory
    # overwrite self-signed certs included with apache
    