  api:
    environment:
      - SIMULATE_SENSORS: ""
  certbot:
    build: ./certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /certificates:/certificates
      - acme-challenge:/webroot/.well-known/acme-challenge
