version: '3'
services:
  api:
    environment:
      - SIMULATE_SENSORS=
  webserver:
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=njms.rocks
      - EMAIL=tech-in-med@njms.rutgers.edu
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
volumes:
  acme-challenge: {}
