version: '3'
services:
  api:
    build: ./api
    environment:
      SIMULATE_SENSORS: please do
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /db
    volumes:
      - "/db:/db" #share /db with host
  webserver:
    restart: always
    build: ./webserver
    ports:
      - 8080:80
      - 8443:443
  3dprinting-ssh-proxy:
    build: 
      context: ./3dprinting/
      dockerfile: ssh-reverse-proxy.Dockerfile
    volumes: 
      - /opt/njms.rocks/3dprinting_host_keys:/etc/ssh/host_keys
    ports:
      - "2222:22"
  3dprinting-webcam-stream-cache:
    build: 
      context: ./3dprinting/
      dockerfile: webcam-stream.Dockerfile
    environment:
      STREAM_SOURCE_URL: http://3dprinting-ssh-proxy:8080/webcam/?action=stream
    depends_on:
      - webserver
      - 3dprinting-ssh-proxy
